config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    get 'pdf'
    post 'pdf_raport'
  end
  resources :item_groups
  resources :item_types
  resources :items do
    get 'service'
    post 'add_history'
  end

  # custom routes
  get 'item_barcodes' => 'items#index_barcodes'
  get 'ajax' => 'items#ajax'
  get 'change_status' => 'items#change_status'
  get 'panel' => 'home#scan'
  get 'schedule' => 'home#schedule_pdf'
  get 'schedule_m' => 'home#schedule_m_pdf'
  get 'orders_panel' => 'orders#panel'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @now = Time.now
    @order_count      = Order.count
    @orders           = Order.where.not(status: ORDER_DONE, id: 1).order(:date_to)
    @from             = -3
    @to               = 7
    @groups           = schedule_groups

    @from_m = (set_from_time(1) - @now).to_i/60/60/24 ; 
    @to_m = -(@now - (@now + 2.months).end_of_month).to_i/60/60/24; 
    @step_m = (@to_m - @from_m) / 7 
  end

  def scan
  end

  def schedule_pdf
    @from   = params[:from].to_i - Time.now.wday + 1
    @to     = params[:to].to_i - Time.now.wday
    @groups = schedule_groups
    render pdf: ["Harmonogram", Time.now.strftime("%d-%m")].join('-'), 
           encoding: 'utf8',
           orientation: 'Landscape',
           background: true,
           no_background: false,
           grayscale: false,
           lowquality: false
  end

  def schedule_m_pdf
    @from   = params[:from].to_i
    @to     = params[:to].to_i
    @groups = schedule_groups
    @step   = (@to - @from) / 7
    render pdf: ["Harmonogram", Time.now.strftime("%d-%m")].join('-'), 
           encoding: 'utf8',
           orientation: 'Landscape',
           background: true,
           no_background: false,
           grayscale: false,
           lowquality: false
  end
  private

  def schedule_groups
  	groups = {}
    # item_groups_ending = ItemGroup.includes(:items).includes(:items => [ :orders ])\
    #   .where(items: {status: [ITEM_BUSY, ITEM_RESERVED]})\
    #   .where(orders: {date_to: Time.now + @from.days .. Time.now + @to.days})
    # item_groups_starting = ItemGroup.includes(:items).includes(:items => [ :orders ])\
    #   .where(items: {status: [ITEM_BUSY, ITEM_RESERVED]})\
    #   .where(orders: {date_from: Time.now + @from.days .. Time.now + @to.days})
    # (item_groups_ending + item_groups_starting).each do |item_group|
    
    #where(date_to: Time.now + @from.days .. Time.now + @to.days)
    (
      Order.where(date_from: (Time.now - 2.months)..Time.now)\
      +\
      Order.where(date_to: (Time.now..(Time.now+2.months)))
    ).each do |order|
      # gather order information here
      groups[order.id] = {id: order.id, orders: [order]} if groups[order.id].nil?
      
    end
    return groups
  end

  def set_from_time(n)
    month_wday = (@now - 1.months).beginning_of_month.wday
    puts month_wday

    day_from = (@now - 1.months).beginning_of_month  + (8 - month_wday + 1).days

  end
end

app/views/home/_schedule.html.erb
<div class="panel panel-white">
  <div class="panel-heading clearfix">
    <h4 class="panel-title">
      Harmonogram 
      <div class="btn-group">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false" style="margin-left: 20px">
          Generuj PDF 
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li>
            <%= link_to schedule_path(from: -7, to: 0) do %>
              Poprzedni tydzień 
              (<%= (Time.now - 7.days - Time.now.wday.days + 1.days).strftime("%d-%m") %>
               - <%= (Time.now + 0.days - Time.now.wday.days).strftime("%d-%m") %>)
            <% end %>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to schedule_path(from: 0, to: 7) do %>
              Obecny tydzień 
              (<%= (Time.now - Time.now.wday.days + 1.days).strftime("%d-%m") %>
               - <%= (Time.now + 7.days - Time.now.wday.days).strftime("%d-%m") %>)
            <% end %>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to schedule_path(from: 7, to: 14) do %>
              Następny tydzień 
              (<%= (Time.now + 7.days- Time.now.wday.days + 1.days).strftime("%d-%m") %>
               - <%= (Time.now + 14.days - Time.now.wday.days).strftime("%d-%m") %>)
            <% end %>
          </li>
          <li>
            <%= link_to schedule_path(from: 14, to: 21) do %>
              Za 2 tygodnie 
              (<%= (Time.now + 14.days- Time.now.wday.days + 1.days).strftime("%d-%m") %>
               - <%= (Time.now + 21.days - Time.now.wday.days).strftime("%d-%m") %>)
            <% end %>
          </li>
          <li>
            <%= link_to schedule_path(from: 21, to: 28) do %>
              Za 3 tygodnie 
              (<%= (Time.now + 21.days- Time.now.wday.days + 1.days).strftime("%d-%m") %>
               - <%= (Time.now + 28.days - Time.now.wday.days).strftime("%d-%m") %>)
            <% end %>
          </li>
        </ul>
      </div>
    </h4>
      
  </div>
  <div class="panel-body">
    <table class="schedule-table" style="">
      <thead>
        <tr>
          <th></th>
          <% (-2..5).each do |i| %>
          <th class="<%= i == 0 ? 'now' : '' %>">
            <div class="text-center">
              <%= wday_local Time.now.wday + i %><br>
              <small> <%= (Time.now + i.days).strftime("%d-%m") %></small>
            </div>
          </th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% groups.each do |(name, value)| %>
          <tr>
            <th>
              <%= link_to value[:orders][0].name, item_group_path(value[:id]) %>
            </th>
            <% (-2..5).each do |i| %>
              <td class="<%= i == 0 ? 'now' : '' %>" style="vertical-align: top;">
                <% value[:orders].each do |order| %>
                  <% if order.date_from.beginning_of_day <= (Time.now.utc + i.days).beginning_of_day && order.date_to.beginning_of_day >= (Time.now.utc + i.days).beginning_of_day %>
                    <div class="progress <%= bar_helper(order, i)%>" style="height: 40px; margin: auto; margin-top: 1px;">
                      <div class="progress-bar <%= bar_color(order, i) %>" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%; line-height: inherit; font-size: 10px;">
                        <div class="text-center" style="float: left; width: 40px; line-height: 18px; border-right: 1px solid rgba(0,0,0,0.1); padding-left: 3px;">
                          <% if order.date_from.mday == (Time.now + i.days).mday && order.date_to.mday == (Time.now + i.days).mday %>
                            <%= order.date_from.strftime("%H:%M") %><br><%= order.date_to.strftime("%H:%M") %>
                          <% elsif order.date_from.mday == (Time.now + i.days).mday %>
                            <%= order.date_from.strftime("%H:%M") %><br><i class="fa fa-minus" aria-hidden="true"></i>
                          <% elsif order.date_to.mday == (Time.now + i.days).mday %>
                            <i class="fa fa-minus" aria-hidden="true"></i><br><%= order.date_to.strftime("%H:%M") %>
                          <% else %>
                            <i class="fa fa-minus" aria-hidden="true"></i><br><i class="fa fa-minus" aria-hidden="true"></i><!-- <i class="fa fa-minus" aria-hidden="true"></i> -->
                          <% end %>
                        </div>
                        <div class="text-left" style="margin-left: 45px; line-height: 18px; padding-left: 3px; font-weight: 100;white-space: nowrap;flex-wrap: nowrap;">
                          <%= value[:orders][0].name %><br><%= order.owner %>
                        </div>
                      </div>
                    </div>
                  <% else %>
                    <div class="progress <%= bar_helper(order, i)%>" style="height: 40px; margin: auto; margin-top: 1px;">
                      <div class="progress-bar progress-bar-dummy <%= i == 0 ? 'now' : '' %>" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%; line-height: inherit; font-size: inherit;">
                      </div>
                    </div>
                  <% end %>
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/home/_schedule_month.html.erb
<div class="panel panel-white">
  <div class="panel-heading clearfix">
    <h4 class="panel-title">
      Harmonogram - wersja miesięczna testowa
      <div class="btn-group">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false" style="margin-left: 20px">
          Generuj PDF 
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li>
            <%= link_to schedule_m_path(from: @from_m, to: @to_m) do %>
              Ten okres 
              (<%= (@now - 2.months).beginning_of_month.strftime("%d-%m") %>
               - <%= (@now + 2.months).beginning_of_month.strftime("%d-%m") %>)
            <% end %>
          </li>
        </ul>
      </div>
    </h4>
  </div>
  <div class="panel-body">
    <table class="schedule-table-big" style="">
      <thead>
        <tr>
          <th colspan="<%= @step_m %>"></th>
          <% (@from_m..@to_m).each do |i| %>
            <% if (@now + i.days).mday == 1 || i == @from_m %>
              <th class="<%= i == 0 ? 'now' : '' %>" style="" colspan=<%= i == @from_m ? (@now + i.days).end_of_month.mday - (@now + i.days).mday : (@now + i.days).end_of_month.mday %> >
                <div class="text-left">
                  <%#= wday_local @now.wday + i %><br>
                  <small> <%= mday_local (@now + i.days).month %></small>
                </div>
              </th>
            <% end %>
          <% end %>
        </tr>
      </thead>
      <thead>
        <tr>
          <th colspan="<%= @step_m %>"></th>
          <% (@from_m..@to_m).each do |i| %>
            <% if wday_local(@now.wday + i) == 'Pon' %>
              <th class="<%= i == 0 ? 'now' : '' %>" style="<%= (wday_bgcolor @now.wday + i) %>" colspan=7>
                <div class="text-left">
                  <%#= wday_local @now.wday + i %><br>
                  <small> <%= (@now + i.days).strftime("%d-%m") %></small>
                </div>
              </th>
            <% end %>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% groups.each do |(name, value)| %>
          <tr>
            <th colspan="<%= @step_m %>">
              <%= link_to value[:orders][0].name, item_group_path(value[:id]) %><br>
              <small style="top: -7px; position: relative;"><%= value[:orders][0].owner %> </small>
            </th>
            <% (@from_m..@to_m).each do |i| %>
              <td class="<%= i == 0 ? 'now-m' : '' %> hover" style="vertical-align: top; <%= (wday_bgcolor @now.wday + i) %>" 
                data-toggle="tooltip" data-placement="top" title="<%= (@now + i.days).strftime("%d-%m")%>">

                  <% if value[:orders].map{|q| q.date_from}.min.beginning_of_day <= (@now.utc + i.days).beginning_of_day && value[:orders].map{|q| q.date_to}.max.beginning_of_day >= (@now.utc + i.days).beginning_of_day %>
                    <div class="progress" style="height: 25px; margin: auto; margin-top: 1px;">
                      <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%; line-height: inherit; font-size: 10px; background-color: <%= progressbar_color(value[:orders][0]) %>;">


                      </div>
                    </div>
                  <% else %>
                    
                  <% end %>

              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/home/index.html.erb
<style>
  .now {background-color: #f6f6f6 !important;}
  .now-m {background-color: #eee !important;}
  .hover:hover{
    background-color: #ddd !important;
  }
  .schedule-table tbody tr td { padding: 5px 0px; }
  .schedule-table {table-layout: fixed; width: 100%;}
  
  .schedule-table tbody tr td {
    border-bottom: 1px solid #ddd;
    border-right: 1px solid #ddd;
  }
  .schedule-table tbody tr th {
    border-bottom: 1px solid #ddd;
    border-right: 1px solid #ddd;
  }
  .schedule-table thead tr th {
    border-bottom: 1px solid #ddd;
    border-right: 1px solid #ddd;
  }
  .bar-start { margin-left: 20px !important; }
  .bar-end { margin-right: 20px !important; }
  .progress-bar-dummy { background-color: rgba(255, 255, 255, 255) }

  .schedule-table-big tbody tr td { padding: 5px 0px; }
  .schedule-table-big {table-layout: fixed; width: 100%;}
  
  .schedule-table-big tbody tr td {
    border-bottom: 1px solid #ddd;
    border-right: 0px solid #ddd;
  }
  .schedule-table-big tbody tr th {
    min-width:300px;
    border-bottom: 1px solid #ddd;
    border-right: 1px solid #ddd;
  }
  .schedule-table-big thead tr th {
    border-bottom: 1px solid #ddd;
    border-right: 1px solid #ddd;
  }

  </style>

<div class="page-inner">
  <div class="page-title">
      <h3 class="breadcrumb-header">Tablica</h3>
  </div>
  <div id="main-wrapper">
    <div class="row">
      <div class="col-lg-12 col-md-12">
        <%= render 'schedule', groups: @groups %>
      </div>
    </div><!-- Row -->
    <div class="row">
      <div class="col-lg-12 col-md-12">
        <%= render 'schedule_month', groups: @groups %>
      </div>
    </div><!-- Row -->
  </div>

</div>
<script>
$('#reveal-items').on('click', function(){
  $(this).slideUp()
  $('.item-list').slideDown();
})
$('#reveal-orders').on('click', function(){
  $(this).slideUp()
  $('.order-list').slideDown();
})
</script>

app/views/home/scan.html.erb
<style>
  .bootstrap-tagsinput input {
    width: 95% !important;
  }
  table tr td {
    padding: 5px;
  }

  .item {
    margin: 2px;
  }

  .card {
    width: 100%;
    height: 100%;
    transition: transform 1s;
    transform-style: preserve-3d;
  }

  .card.is-flipped {
    transform: rotateY(180deg);
  }

  .card-face {
    position: fixed;
    backface-visibility: hidden;
  }

  .card-back {
    transform: rotateY(180deg);
    left: -3px;
  }

  .card-front {
  }
</style>
<div class="page-inner">
  <div class="page-title">
    <h3 class="breadcrumb-header">Zdaj sprzęt</h3>
  </div>
  <div id="main-wrapper">
    <div class="row">
      <div class="col-lg-12">
        <%= bootstrap_form_for(Item.new) do |f| %>
          <div id="focus-id">
            <%= f.text_field :ean, label: nil, hide_label: true, 'data-role' => 'tagsinput' %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-white">
          <div class='panel-heading'>
            <h4 class='panel-title'>Sprzęt zdany</h4>
          </div>
          <div class="panel-body">
            <div class="row items-container"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>

    // fucus input even if lost
    setTimeout(function () {
        $('input:text')[1].focus();
        $('#focus-id').on('focusout', function () {
            $('input:text')[1].focus();
        })
    }, 500);

    $('input:text').on('itemAdded', function (event) {
        // event.item: contains the item

        $.get('/ajax?back=1&ean=' + event.item, function (data) {
            if (data.length > 100) {
                $('.items-container').append(data)
                toastr.success('Zwrócono przedmiot', 'Sukces');
            } else {
                toastr.error('Przedmiot nie dostępny', 'Błąd');
            }
        })


        // remove removal from tags input
        $('span[data-role=remove]').hide()
    });
</script>

app/views/home/schedule_m_pdf.html.erb
<style>
  .now { }
  .schedule-table-big tbody tr td { padding: 5px 0px; }
  .schedule-table-big {table-layout: fixed; width: 100%; border-collapse: collapse;}
  
  .schedule-table-big tbody tr td {
    border-bottom: 1px solid #ddd;
    border-right: 0px solid transparent;
  }
  .schedule-table-big tbody tr th {
    min-width:300px;
    border-bottom: 1px solid #ddd;
    border-right: 1px solid #ddd;
  }
  .schedule-table-big thead tr th {
    border-bottom: 1px solid #ddd;
    border-right: 1px solid #ddd;
  }
  .bar-start { margin-left: 20px !important; }
  .bar-end { margin-right: 20px !important; }
  .progress-bar-dummy { background-color: transparent; border: 0px !important; }
  thead { display: table-header-group }
  tfoot { display: table-row-group }
  tr { page-break-inside: avoid }
  .progress-bar {text-overflow: clip; white-space: nowrap; overflow: hidden;}
</style>
<div class="row">
  <div class="col-lg-12 col-md-12">
    <div class="panel panel-white">
      <div class="panel-body">
        <table class="schedule-table-big" style="">
          <thead>
            <tr>
              <th colspan="<%= @step %>" rowspan=2 style="width:180px;"><p style="text-align: center; color: #0070E0 !important"><b>HARMONOGIO</b></p></th>
              <% (@from..@to).each do |i| %>
                <% if (@now + i.days).mday == 1 || i == @from %>
                  <th class="<%= i == 0 ? 'now' : '' %>" style="" colspan=<%= i == @from ? (@now + i.days).end_of_month.mday - (@now + i.days).mday : (@now + i.days).end_of_month.mday %> >
                    <div class="text-left">
                      <%#= wday_local @now.wday + i %><br>
                      <small> <%= mday_local (@now + i.days).month %></small>
                    </div>
                  </th>
                <% end %>
              <% end %>
            </tr>
          </thead>
          <thead>
            <tr>
              <th colspan="<%= @step %>"></th>
              <% (@from..@to).each do |i| %>
                <% if wday_local(@now.wday + i) == 'Pon' %>
                  <th class="<%= i == 0 ? 'now' : '' %>" style="<%= (wday_bgcolor @now.wday + i) %>" colspan=7 width="30">
                    <div class="text-left">
                      <%#= wday_local @now.wday + i %><br>
                      <small> <%= (@now + i.days).strftime("%d-%m") %></small>
                    </div>
                  </th>
                <% end %>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <% @groups.each do |(name, value)| %>
              <tr>
                <th colspan="<%= @step %>">
                  <pre><%= value[:orders][0].name %></pre>
                  <small style="top: -10px; position: relative; white-space: nowrap; font-weight: 100; line-height: 1px;"><%= value[:orders][0].owner %> </small>
                </th>
                <% (@from..@to).each do |i| %>
                  <td class="<%= i == 0 ? 'now-m' : '' %> hover" style="vertical-align: top; <%= (wday_bgcolor @now.wday + i) %>" >

                      <% if value[:orders].map{|q| q.date_from}.min.beginning_of_day <= (@now.utc + i.days).beginning_of_day && value[:orders].map{|q| q.date_to}.max.beginning_of_day >= (@now.utc + i.days).beginning_of_day %>
                        <div class="progress" style="height: 25px; margin: 0px; margin-top: 1px;">
                          <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%; line-height: inherit; font-size: 10px; background-color: <%= progressbar_color(value[:orders][0]) %>;">
                            &nbsp;

                          </div>
                        </div>
                      <% else %>
                        
                      <% end %>

                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div><!-- Row -->

app/views/home/schedule_pdf.html.erb
<style>
  .now { }
  .schedule-table tbody tr td { padding: 5px 0px; }
  .schedule-table {table-layout: fixed; width: 100%; border-collapse: collapse}
  
  .schedule-table tbody tr td {
    border-bottom: 1px solid #ddd;
    border-right: 1px solid #ddd;
  }
  .schedule-table tbody tr th {
    border-bottom: 1px solid #ddd;
    border-right: 1px solid #ddd;
  }
  .schedule-table thead tr th {
    border-bottom: 1px solid #ddd;
    border-right: 1px solid #ddd;
  }
  .bar-start { margin-left: 20px !important; }
  .bar-end { margin-right: 20px !important; }
  .progress-bar-dummy { background-color: transparent; border: 0px !important; }
  thead { display: table-header-group }
	tfoot { display: table-row-group }
	tr { page-break-inside: avoid }
  .progress-bar {text-overflow: clip; white-space: nowrap; overflow: hidden;}
</style>
<div class="row">
  <div class="col-lg-12 col-md-12">
    <div class="panel panel-white">
      <div class="panel-body">
        <table class="schedule-table" style="">
          <thead>
            <tr>
              <th><p style="text-align: center; color: #0070E0 !important"><b>HARMONOGIO</b></p></th>
              <% (@from .. @to).each do |i| %>
              <th class="<%= i == 0 ? 'now' : '' %>">
                <div class="text-center">
                  <%= wday_local Time.now.wday + i %><br>
                  <small> <%= (Time.now + i.days).strftime("%d-%m") %></small>
                </div>
              </th>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <% @groups.each do |(name, value)| %>
              <tr>
                <th>
                  <%= value[:orders][0].name %>
                </th>
                <% (@from.. @to).each do |i| %>
                  <td class="<%= i == 0 ? 'now' : '' %>" style="vertical-align: top;">
                    <% value[:orders].each do |order| %>
                      <% if order.date_from.beginning_of_day <= (Time.now.utc + i.days).beginning_of_day && order.date_to.beginning_of_day >= (Time.now.utc + i.days).beginning_of_day %>
                        <div class="progress <%= bar_helper(order, i)%>" style="height: 40px; margin: auto; margin-top: 1px;">
                          <div class="progress-bar <%= bar_color(order, i) %>" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%; line-height: inherit; font-size: 10px; background-color: <%= bar_color_pdf(order, i) %>;">
                            <div class="text-center" style="float: left; width: 40px; line-height: 18px; padding-left: 3px;">
                              <% if order.date_from.beginning_of_day == (Time.now.utc + i.days).beginning_of_day && order.date_to.beginning_of_day == (Time.now.utc + i.days).beginning_of_day %>
                                <%= order.date_from.strftime("%H:%M") %><br><%= order.date_to.strftime("%H:%M") %>
                              <% elsif order.date_from.beginning_of_day == (Time.now.utc + i.days).beginning_of_day %>
                                <%= order.date_from.strftime("%H:%M") %><br>---
                              <% elsif order.date_to.beginning_of_day == (Time.now.utc + i.days).beginning_of_day %>
                                ---<br><%= order.date_to.strftime("%H:%M") %>
                              <% else %>
                                ---<br>---
                              <% end %>
                            </div>
                            <div class="text-left" style="margin-left: 45px; line-height: 18px; padding-left: 3px; font-weight: 100;white-space: nowrap; flex-wrap: nowrap; ">
                              <%= value[:orders][0].name %><br><%= order.owner %>
                            </div>
                          </div>
                        </div>
                      <% else %>
                        <div class="progress <%= bar_helper(order, i)%>" style="height: 40px; margin: auto; margin-top: 1px;">
                          <div class="progress-bar progress-bar-dummy <%= i == 0 ? 'now' : '' %>" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%; line-height: inherit; font-size: inherit;">
                          </div>
                        </div>
                      <% end %>
                    <% end %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div><!-- Row -->